//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MBackProp.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MBACKPROP_DIALOG            102
#define IDS_VERSION                     103
#define IDR_MAINFRAME                   128
#define IDD_RANDWEIGHTS                 130
#define IDD_LOADSAVE                    132
#define IDD_LEARNING_MOMENTUM           137
#define IDD_WEIGHTS_DIALOG              139
#define IDD_GRID_DIALOG                 140
#define IDR_VERSION                     141
#define IDTRAIN                         1000
#define IDC_TrainFileBox                1001
#define IDC_TestFileBox                 1002
#define IDC_BPTOPOLOGYCTRL              1003
#define IDC_LEARNING                    1004
#define IDC_INITIALWEIGHT               1005
#define IDC_MAIN_NET_LEARNING           1006
#define IDC_MAIN_LEARNING               1007
#define IDC_FINALWEIGHT                 1008
#define IDC_MAIN_NET_MOMENTUM           1009
#define IDC_SPACE_LEARNING              1010
#define IDC_MOMENTUM                    1011
#define IDC_SPACE_NET_LEARNIG           1012
#define IDC_MAIN_MOMENTUM               1013
#define IDC_SPACE_NET_MOMENTUM          1014
#define IDC_SPACE_MOMENTUM              1015
#define IDC_RMS_TO_STOP                 1016
#define IDC_EPOCH                       1017
#define IDC_UP_DBD                      1018
#define IDC_TRAIN_RMS                   1019
#define IDC_RMS_GROW_PERCENT            1020
#define IDSTOP                          1021
#define IDC_DOWN_DBD                    1022
#define IDRANDOMIZEWEIGHTS              1023
#define IDC_DOWN_DBD2                   1023
#define IDC_MAX_STEPSIZE                1023
#define IDC_ROBUSTNESS_LR_REDUCE        1024
#define IDC_TEST_RMS                    1025
#define IDC_SPACE_RMS_TO_STOP           1026
#define IDLOADWEIGHTS                   1027
#define IDC_WEIGHT_DECAY                1028
#define IDC_TAB                         1029
#define IDSAVEWEIGHTS                   1030
#define IDC_FRAMEDATAFILES              1031
#define IDC_FRAMEEPOCH                  1032
#define IDC_FRAMERMS                    1033
#define IDC_LABEL_TRAINRMSDISPLAY       1034
#define IDC_LABEL_TESTRMSDISPLAY        1035
#define IDC_LEARNINGFRAME               1036
#define IDC_MAINNETLEARNINGFRAME        1037
#define IDC_LABEL_LEARNING              1038
#define IDC_LABEL_MAIN_LEARNING         1039
#define IDC_LABEL_MOMENTUM              1040
#define IDC_LABEL_MAIN_MOMENTUM         1041
#define IDC_FRAME_WEIGHTS               1042
#define IDC_FILEBOX                     1043
#define IDC_FRAME_NETWORK               1044
#define IDCCODE                         1045
#define IDC_MAIN_NET_LEARN_PERC_DECAY   1046
#define IDLOADNETWORK                   1047
#define IDC_MAIN_NET_MOM_PERC_DECAY     1048
#define IDSAVENETWORK                   1049
#define IDC_MAIN_NET_LEARN_EPOCH_DECAY  1050
#define IDC_MAIN_NET_MOM_EPOCH_DECAY    1051
#define IDLEARNINGMOMENTUM              1052
#define IDC_SPACE_NET_LEARNIG_PERC_DECAY 1053
#define IDC_SPACENETLEARNINGFRAME       1054
#define IDC_SPACE_NET_LEARNIG_EPOCH_DECAY 1055
#define IDC_LABEL_SPACE_LEARNING        1056
#define IDC_SPACE_NET_MOMENTUM_PERC_DECAY 1057
#define IDC_LABEL_SPACE_MOMENTUM        1058
#define IDC_SPACE_NET_MOMENTUM_EPOCH_DECAY 1059
#define IDC_FRAMELEARNING               1060
#define IDVIEWWEIGHTS                   1061
#define IDC_AUTO_UPDATE                 1062
#define IDC_AUTO_UPDATE_LEARNING        1063
#define IDC_MAINFRAME                   1064
#define IDC_MAINNETRMSFRAME             1065
#define IDC_SPACEFRAME                  1066
#define IDC_SPACENETRMSFRAME            1067
#define IDC_EPOCHSCAPTION               1068
#define IDC_LABEL_TRAINRMSDISPLAY_SPACE 1068
#define IDC_TRAIN_RMS_SPACE             1070
#define IDC_WEIGHTS_GRID                1071
#define IDC_RANDOMIZE_PATTERNS          1072
#define IDC_GRID                        1073
#define IDC_LABEL_TESTRMSDISPLAY_SPACE  1074
#define IDC_LM_CONF                     1075
#define IDC_TEST_RMS_SPACE              1076
#define IDC_STOP_RMS                    1077
#define IDC_STOP_EPOCHS                 1078
#define IDSENSIVITY                     1079
#define IDC_EPOCHS_TO_STOP              1080
#define IDC_DELTA_BAR_DELTA             1081
#define IDC_BATCH                       1082
#define IDC_ONLINE                      1083
#define IDC_LM_CONF2                    1084
#define IDC_MAINFRAME2                  1085
#define IDC_AUTO_UPDATE_MOMENTUM        1086
#define IDC_ROBUSTNESS                  1087
#define IDC_LB_MLR                      1088
#define IDC_LB_MM                       1089
#define IDC_LB_SLR                      1090
#define IDC_LB_SM                       1091
#define IDC_CRITICAL_THREAD             1092
#define IDC_UPDATE_SCREEN               1093
#define IDC_THREAD                      1094
#define IDC_MSFLEXGRID1                 1095
#define IDC_GRAPHIC1                    1096
#define IDC_CHECK1                      1097
#define IDC_ENABLE_CUDA                 1098

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
